#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
[[ " help $PLUGIN_COMMAND_PREFIX:help " == *" $1 "* ]] || [[ "$1" == "$PLUGIN_COMMAND_PREFIX:"* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_BASE_PATH/common/functions"

if [[ ! -d $PLUGIN_DATA_ROOT ]]; then
  dokku_log_fail "$PLUGIN_SERVICE: Please run: sudo dokku plugin:install"
fi

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"

COMMAND=${1:-}
shift 1
case "$COMMAND" in
  $PLUGIN_COMMAND_PREFIX:admin)
		access_admin
    ;;
  $PLUGIN_COMMAND_PREFIX:admin-add)
    access_admin_add $@
    ;;
  $PLUGIN_COMMAND_PREFIX:admin-remove)
    access_admin_remove $@
    ;;
  $PLUGIN_COMMAND_PREFIX:admin-removeAll)
    access_admin_remove_all
    ;;
  $PLUGIN_COMMAND_PREFIX:git)
    access_git $@
    ;;
  $PLUGIN_COMMAND_PREFIX:git-add)
    access_git_add $@
    ;;
  $PLUGIN_COMMAND_PREFIX:git-remove)
    access_git_remove $@
    ;;
  $PLUGIN_COMMAND_PREFIX:git-removeAll)
    access_git_remove_all $@
    ;;
  help | $PLUGIN_COMMAND_PREFIX:help)
    help_content_func() {
      cat<<help_content
    $PLUGIN_COMMAND_PREFIX:admin, Show list of admins with access to run all command
    $PLUGIN_COMMAND_PREFIX:admin-add <user>, Allow users access to run all command
    $PLUGIN_COMMAND_PREFIX:admin-remove <user>, Revoke users access to run all command
    $PLUGIN_COMMAND_PREFIX:admin-removeAll, Revoke all users access to run all command
    $PLUGIN_COMMAND_PREFIX:git <app>, Show list of users with access to app repository
    $PLUGIN_COMMAND_PREFIX:git-add <app> <user>, Allow user access to the app repository
    $PLUGIN_COMMAND_PREFIX:git-remove <app> <user>, Revoke users access to the app repository
    $PLUGIN_COMMAND_PREFIX:git-removeAll <app>, Revoke all users access to the app repository
help_content
	}
	if [[ $COMMAND = "$PLUGIN_COMMAND_PREFIX:help" ]] ; then
		echo -e "Usage: dokku $PLUGIN_COMMAND_PREFIX:[:COMMAND]"
		echo ''
		echo 'Commands:'
		help_content_func | column -c2 -t -s,
	elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
		help_content_func
	else
		cat<<help_desc
    $PLUGIN_COMMAND_PREFIX, Plugin for adding user access control (Command permission & Git - push/pull for each App)
help_desc
	fi
    ;;
	*)
		exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
		;;
esac



